[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_hatcher = "8EgjF9Ema9VpR2XFqsPt591n5rvgBDJqB1dGHdVJhFm9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zeppelin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 2000 tests/**/sol-hatcher.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/metadata.so"